### ISSUE TITLE
[0.5pt] Add header - group task

### ISSUE THREAD

**Issue by PabloBona** [PabloBona/JavaScriptCapstone#17]
Create page header according to the wireframe:

<img width="541" alt="Screenshot 2021-06-27 at 21 42 24" src="https://user-images.githubusercontent.com/7466903/123557332-ac3eee80-d790-11eb-91c8-9f8a6a38a4ff.png">

**Comment by NitBravoA92** [comment]
# Request a Review 👨‍💻

Pull Request: [Add header section](https://github.com/PabloBona/JavaScriptCapstone/pull/22)

# ⭐To my dear partner 

@PabloBona Thank you so much for taking the time to review these implementations, I really appreciate it. I kindly ask you 🙏 that if there is any issue 🦯 in this milestone, please do list 📃 them in a descriptive 💡 manner and give all your suggestions and recommendations.🎁 I will be happy to apply the changes that are necessary.

If you think there is a big change that needs to be made ♻️ please kindly contact 📞 me through Zoom or Slack to 
discuss it and apply it.

**Comment by NitBravoA92** [comment]
Updates approved!
